name: check_it_off
description: A new Flutter application.

version: 1.0.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  provider: ^4.3.2+2
  sqflite: any
  path_provider: ^1.6.18
  introduction_screen: ^1.0.9
  splashscreen: ^1.2.0
  shared_preferences: ^0.5.12
  url_launcher: ^5.7.2
  rflutter_alert: ^1.1.0
  add_2_calendar: ^1.4.0
  toggle_switch: ^0.1.8
  numberpicker: ^1.2.1
  device_calendar: ^3.1.0
  add_to_calendar: ^1.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/onboarding/
