name: check_it_off
description: A new Flutter application.

version: 1.0.4+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  provider: ^4.3.2+2
  sqflite: ^1.3.1+1
  path_provider: ^1.6.18
  introduction_screen: ^1.0.9
  splashscreen: ^1.2.0
  shared_preferences: ^0.5.12
  url_launcher: ^5.7.2
  rflutter_alert: ^1.1.0
  toggle_switch: ^0.1.8
  numberpicker: ^1.2.1
  device_calendar: ^3.1.0
  add_to_calendar: ^1.2.0+1
  flutter_switch: ^0.1.3
  quick_actions: ^0.4.0+10
  flutter_local_notifications: ^2.0.1
  rxdart: ^0.24.1
  redux: ^4.0.0+3
  redux_persist: ^0.8.4
  flutter_redux: ^0.6.0
  background_fetch: ^0.6.0
  recase: ^3.0.0
  timezone: ^0.5.7
  flutter_native_timezone: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/onboarding/
